language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "8"
before_install:
  - "npm i -g tiddlywiki@5.1.21"
  - "git clone https://github.com/danielo515/tw5-pouchdb.git pouchdb" # note that I'm naming the output folders for easier reference later
  - "git clone https://github.com/danielo515/tiddlypouch.git tpouch"
  - "ls -l"
before_script:
 - export TIDDLYWIKI_PLUGIN_PATH="$(pwd)/plugins:$(pwd)/pouchdb/src/plugins:$(pwd)/tpouch/dist" # Plugins paths with all deps globally available
 - "(cd tpouch && npm i && gulp travis --production)"
script:
 # ===== Builds NoteSelf core plugins
 - npm run build-plugin 
 # ===== Build the editions
 - tiddlywiki ./wiki --verbose --output ./dist --build index --build favicon --build library
 - ./build-editions.sh
 # ===== Non Minified version =====
 - "(cd ./tpouch && gulp travis)" # Build non minified version of TPouch code ( no --production flag )
 - tiddlywiki ./editions/online --verbose --build dev # This is the same as the online one, but to a different dist path
 # ===== Build edge version with the latest tiddlywiki and experimental plugins =====
 - "npm i tiddlywiki@latest  && npx tiddlywiki --version"
 - "npx tiddlywiki ./editions/edge --verbose --build index" # build the edge edition (includes not well tested stuff)
 # === Measures file sizes and adds that data to the pull request ===
 - |
    for edition in $(ls dist); do
      python node_modules/travis-weigh-in/weigh_in.py dist/${edition}/index.html || true
    done
 - python node_modules/travis-weigh-in/weigh_in.py dist/index.html || true
 - python node_modules/travis-weigh-in/weigh_in.py dist/offline.html || true
after_script:
 - "ls -lR dist"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./dist
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop
